- 3주차/bongJ/BOJ10026.java
- 3주차/bongJ/BOJ1012.java
- 3주차/bongJ/BOJ1181.java
- 3주차/bongJ/BOJ7562.java
- 3주차/bongJ/BOJ7569.java
> 3주차-장봉준-1181

- 2주차/yeseul/BOJ_5648.java
- 3주차/yeseul/BOJ_10026.java
- 3주차/yeseul/BOJ_1012.java
- 3주차/yeseul/BOJ_1181.java
- 3주차/yeseul/BOJ_2910.java
- 3주차/yeseul/BOJ_5427.java
- 3주차/yeseul/BOJ_7562.java
- 3주차/yeseul/BOJ_7569.java
- README.md
> 3주차-이예슬-0615

- 2주차/seyeong/BOJ_5648.java
- 3주차/seyeong/BOJ_10026.java
- 3주차/seyeong/BOJ_1012.java
- 3주차/seyeong/BOJ_1181.java
- 3주차/seyeong/BOJ_2910.java
- 3주차/seyeong/BOJ_7562.java
- 3주차/seyeong/BOJ_7569.java
> 3주차-홍세영-0615

- 4주차/juyoung
> 4주차-김주영-0619

- 4주차/yeseul/BOJ_1600.java
- 4주차/yeseul/BOJ_2136.java
- 4주차/yeseul/BOJ_2206.java
- 4주차/yeseul/BOJ_2573.java
- 4주차/yeseul/BOJ_9466.java
- 5주차/yeseul/BOJ_2606.java
N주차-이름-날짜 
---
2206번: 벽을 부수고 지났을 때, 부수지 않고 지났을 때를 visited배열의 삼중배열이 아닌 다른 형태로 처리해 풀 수 있을까요...........?.............
> 4주차-이예슬-0620

- 3주차/daeho/BJ_5427.java
- 3주차/daeho/BJ_7562.java
- 4주차/daeho/BJ_13549.java
- 4주차/daeho/BJ_1600.java
- 4주차/daeho/BJ_2146.java
- 4주차/daeho/BJ_2206.java
- 4주차/daeho/BJ_9466.java
> 4주차-고대호-0622

- 4주차/no2573
- 4주차/주영/no13549.java
- 4주차/주영/no1600
- 5주차/juyoung/no11724.java
- 5주차/juyoung/no13023.java
- 5주차/juyoung/no1967.java
- 5주차/juyoung/no2606.java
- 5주차/juyoung/no2644.java
- 5주차/juyoung/no2668.java
> 5주차-김주영-0629

- 5주차/BJ_11724.java
- 5주차/BJ_13023.java
- 5주차/BJ_2606.java
- 5주차/BJ_2644.java
- 5주차/BJ_2668.java
> 5주차-고대호-0628

- 5주차/yeseul/BOJ_11724.java
- 5주차/yeseul/BOJ_13023.java
- 5주차/yeseul/BOJ_1967.java
- 5주차/yeseul/BOJ_2606.java
- 5주차/yeseul/BOJ_2644.java
- 5주차/yeseul/BOJ_2668.java
- README.md
> 5주차-이예슬-0629

- 4주차/BOJ_13549.java
- 4주차/BOJ_1600.java
- 4주차/BOJ_2146.java
- 4주차/BOJ_2206.java
- 4주차/BOJ_2573.java
- 5주차/BOJ_11724.java
- 5주차/BOJ_13023.java
- 5주차/BOJ_1967.java
- 5주차/BOJ_2606.java
- 5주차/BOJ_2644.java
- 5주차/BOJ_2668.java
> 5주차-홍세영-0629

- 6주차/gahee/BJ_13144.java
- 6주차/gahee/BJ_1644.java
- 6주차/gahee/BJ_2003.java
- 6주차/gahee/BJ_20922.java
- 6주차/gahee/BJ_22862.java
- 6주차/gahee/BJ_2531.java
> 6주차-최가희-0706

- 6주차/juyoung/no13144.java
- 6주차/juyoung/no1644.java
- 6주차/juyoung/no2003.java
- 6주차/juyoung/no20922.java
- 6주차/juyoung/no22862.java
- 6주차/juyoung/no2531.java
>  6주차-김주영-0706

- .idea/.gitignore
- 6주차/yeseul/BOJ_13144.java
- 6주차/yeseul/BOJ_1644.java
- 6주차/yeseul/BOJ_2003.java
- 6주차/yeseul/BOJ_20922.java
- 6주차/yeseul/BOJ_22862.java
- 6주차/yeseul/BOJ_2531.java
> 6주차-이예슬-0706

- 7주차/gahee/BJ1003.java
- 7주차/gahee/BJ11055.java
- 7주차/gahee/BJ_1003.java
- 7주차/gahee/BJ_10844.java
- 7주차/gahee/BJ_11053.java
- 7주차/gahee/BJ_11727.java
- 7주차/gahee/BJ_14501.java
- 7주차/gahee/BJ_15486.java
- 7주차/gahee/BJ_1912.java
- 7주차/gahee/BJ_2193.java
- 7주차/gahee/BJ_9251.java
- 7주차/gahee/BJ_9461.java
> 7주차-최가희-0713

- 7주차/ingyeom/BOJ_1003.java
- 7주차/ingyeom/BOJ_10844.java
- 7주차/ingyeom/BOJ_11053.java
- 7주차/ingyeom/BOJ_11055.java
- 7주차/ingyeom/BOJ_11727.java
- 7주차/ingyeom/BOJ_14501.java
- 7주차/ingyeom/BOJ_15486.java
- 7주차/ingyeom/BOJ_1912.java
- 7주차/ingyeom/BOJ_1932.java
- 7주차/ingyeom/BOJ_2193.java
- 7주차/ingyeom/BOJ_9461.java
> 7주차-정인겸-0714

- 7주차/daeho/BJ_1003.java
- 7주차/daeho/BJ_10844.java
- 7주차/daeho/BJ_11053.java
- 7주차/daeho/BJ_11055.java
- 7주차/daeho/BJ_11727.java
- 7주차/daeho/BJ_14501.java
- 7주차/daeho/BJ_15486.java
- 7주차/daeho/BJ_1912.java
- 7주차/daeho/BJ_1932.java
- 7주차/daeho/BJ_2193.java
- 7주차/daeho/BJ_9461.java
> 7주차-고대호-0713

- 7주차/seyeong/BOJ_1003.java
- 7주차/seyeong/BOJ_10844.java
- 7주차/seyeong/BOJ_11053.java
- 7주차/seyeong/BOJ_11055.java
- 7주차/seyeong/BOJ_11727.java
- 7주차/seyeong/BOJ_14501.java
- 7주차/seyeong/BOJ_15486.java
- 7주차/seyeong/BOJ_1912.java
- 7주차/seyeong/BOJ_1932.java
- 7주차/seyeong/BOJ_2193.java
- 7주차/seyeong/BOJ_9461.java
> 7주차-홍세영-0713

- 7주차/yeseul/BOJ_1003.java
- 7주차/yeseul/BOJ_10844.java
- 7주차/yeseul/BOJ_11053.java
- 7주차/yeseul/BOJ_11055.java
- 7주차/yeseul/BOJ_11727.java
- 7주차/yeseul/BOJ_15486.java
- 7주차/yeseul/BOJ_1912.java
- 7주차/yeseul/BOJ_1932.java
- 7주차/yeseul/BOJ_2193.java
- 7주차/yeseul/BOJ_9461.java
- README.md
N주차-이름-날짜 
**1912번** : 부분 배열의 합을 누적하면서, 현재까지의 최대 부분 배열 합을 지속적으로 갱신하는 카데인의 알고리즘...... 이라는 게 있대요................... 이런 알고리즘의 이름은 처음 들어보네요.........
> 7주차-이예슬-0712

- 7주차/juyoung/no1003.java
- 7주차/juyoung/no10844.java
- 7주차/juyoung/no11053.java
- 7주차/juyoung/no11055.java
- 7주차/juyoung/no11727.java
- 7주차/juyoung/no14501.java
- 7주차/juyoung/no1912.java
- 7주차/juyoung/no1932.java
- 7주차/juyoung/no2193.java
- 7주차/juyoung/no9251.java
- 7주차/juyoung/no9461.java
> 7주차-김주영-0713

- 7주차/bongj/BOJ1003.java
- 7주차/bongj/BOJ10844.java
- 7주차/bongj/BOJ11053.java
- 7주차/bongj/BOJ11055.java
- 7주차/bongj/BOJ11727.java
- 7주차/bongj/BOJ15486.java
- 7주차/bongj/BOJ1912.java
- 7주차/bongj/BOJ1932.java
- 7주차/bongj/BOJ2193.java
- 7주차/bongj/BOJ9461.java
> 7주차_장봉준_0712

- .idea/coding-study.iml
- .idea/uiDesigner.xml
- 7주차/bongj/BOJ10942.java
- 7주차/bongj/BOJ1699.java
- 7주차/bongj/BOJ1915.java
- 7주차/bongj/BOJ9084.java
- 7주차/bongj/BOJ9251.java
- 7주차/bongj/BOJ9655.java
- week 8/week 8.iml
> 8주차_장봉준_0720

- 8주차/BJ_10942.java
- 8주차/BJ_1699.java
- 8주차/BJ_1915.java
- 8주차/BJ_2011.java
- 8주차/BJ_9084.java
- 8주차/BJ_9251.java
- 8주차/BJ_9655.java
> 8주차-고대호-0720

- 8주차/yeseul/BOJ_1699.java
- 8주차/yeseul/BOJ_9251.java
> 8주차-이예슬-0716

- 8주차/juyoung/no10942.java
- 8주차/juyoung/no1699.java
- 8주차/juyoung/no1915.java
- 8주차/juyoung/no2011.java
- 8주차/juyoung/no9084.java
- 8주차/juyoung/no9655.java
> 8주차-김주영-0720

- 9주차/BJ_11559.java
- 9주차/BJ_13335.java
- 9주차/BJ_14499.java
- 9주차/BJ_14891.java
> 9주차-고대호-0725

- 9주차/yeseul/BOJ_11559.java
- 9주차/yeseul/BOJ_13335.java
- 9주차/yeseul/BOJ_14499.java
- 9주차/yeseul/BOJ_14891.java
> 9주차-이예슬-0725

- 9주차/ingyeom/BOJ_11559.java
- 9주차/ingyeom/BOJ_13335.java
- 9주차/ingyeom/BOJ_14499.java
- 9주차/ingyeom/BOJ_14503.java
- 9주차/ingyeom/BOJ_14891.java
- 9주차/ingyeom/BOJ_16985.java
> 9주차-정인겸-0727

- 9주차/seyeong/BOJ_13335.java
- 9주차/seyeong/BOJ_14499.java
- 9주차/seyeong/BOJ_14891.java
- 9주차/seyeong/BOJ_16985.java
- 9주차/seyeong/boj_14503.java
- 9주차/seyeong/rt_11599.java
> 9주차-홍세영-0727

- 10주차/yeseul/BOJ_14500.java
- 10주차/yeseul/BOJ_3190.java
- README.md
> 10주차-이예슬-0730

- 10주차/yeseul/BOJ_13460.java
- 10주차/yeseul/BOJ_14502.java
- 10주차/yeseul/BOJ_14888.java
- 10주차/yeseul/BOJ_14889.java
> 10주차-이예슬-0803

- week10/BOJ14889.java
- week10/bongj/BOJ13460.java
- week10/bongj/BOJ14500.java
- week10/bongj/BOJ14502.java
- week10/bongj/BOJ14888.java
> 10주차_장봉준_0803

- 10주차/daeho/BJ_13460.java
- 10주차/daeho/BJ_14500.java
- 10주차/daeho/BJ_14502.java
- 10주차/daeho/BJ_14888.java
- 10주차/daeho/BJ_14889.java
> 10주차-고대호-0803

- 10주차/seyeong/BOJ_13460.java
- 10주차/seyeong/BOJ_14500.java
- 10주차/seyeong/BOJ_14502.java
- 10주차/seyeong/BOJ_14888.java
- 10주차/seyeong/BOJ_14889.java
- 10주차/seyeong/BOJ_3190.java
> 10주차-홍세영-0803

- 10주차/ingyeom/BOJ_13460.java
- 10주차/ingyeom/BOJ_14500.java
- 10주차/ingyeom/BOJ_14502.java
- 10주차/ingyeom/BOJ_14888.java
- 10주차/ingyeom/BOJ_14889.java
- 10주차/ingyeom/BOJ_3190.java
> 10주차-정인겸-0803

- 11주차/yeseul/BOJ_17142.java
- README.md
> 11주차-이예슬-0805

- 11주차/ingyeom/BOJ_13459.java
- 11주차/ingyeom/BOJ_17142.java
- 11주차/ingyeom/BOJ_19238.java
- 11주차/ingyeom/LTC_Sudoku Solver.java
- 11주차/ingyeom/PGS_블록이동하기.java
- 11주차/ingyeom/PGS_양과늑대.java
> 11주차-정인겸-0810

- 11주차/seyeong/BOJ_13459.java
- 11주차/seyeong/BOJ_17142.java
- 11주차/seyeong/pg_sheepwolf.java
> 11주차-홍세영-0809

- 11주차/daeho/BJ_13459.java
- 11주차/daeho/BJ_17142.java
- 11주차/daeho/PGS_Sudoku Solver.java
- 11주차/daeho/PGS_양과늑대.java
> 11주차-고대호-0810

- .idea/compiler.xml
- .idea/encodings.xml
- .idea/jarRepositories.xml
- .idea/material_theme_project_new.xml
- 11week.iml
- week11/BOJ13459.java
- week11/BOJ17142.java
- week11/BOJ19238.java
- week11/programmers60063.java
> 11주차_장봉준_0808

- 11주차/yeseul/BOJ_13459.java
- 11주차/yeseul/BOJ_19238.java
- 11주차/yeseul/LTC_SudokuSolver/Solution.java
- 11주차/yeseul/PGM_블록이동하기/Solution.java
- 11주차/yeseul/PSM_양과늑대/Solution.java
> 11주차-이예슬-0810

- 11주차/juyoung/no19248.java
> 11주차-김주영-0807

- 11주차/gahee/BJ_19238.java
- 11주차/gahee/Leet_code_스토쿠.java
> 11주차-최가희-0810

- week12/BOJ1238.java
- week12/BOJ1504.java
- week12/BOJ1916.java
> 12주차_장봉준_0814

- 12주차/yeseul/BOJ_1238.java
- 12주차/yeseul/BOJ_1261.java
- 12주차/yeseul/BOJ_1504.java
- 12주차/yeseul/BOJ_17835.java
- 12주차/yeseul/BOJ_1916.java
- 12주차/yeseul/BOJ_20183.java
- README.md
> 12주차-이예슬-0817

- 12주차/seyeong/BOJ_1261.java
- 12주차/seyeong/BOJ_1504.java
- 12주차/seyeong/BOJ_17835.java
- 12주차/seyeong/BOJ_1916.java
- 12주차/seyeong/BOJ_20183.java
- 12주차/seyeong/boj_1238.java
> 12주차-홍세영-0817

- 12주차/daeho/BJ_11779.java
- 12주차/daeho/BJ_1238.java
- 12주차/daeho/BJ_1261.java
- 12주차/daeho/BJ_1504.java
- 12주차/daeho/BJ_17835.java
- 12주차/daeho/BJ_1916.java
> 12주차-고대호-0814

- 12주차/ingyeom/BOJ_1238.java
- 12주차/ingyeom/BOJ_1261.java
- 12주차/ingyeom/BOJ_1504.java
- 12주차/ingyeom/BOJ_1753.java
> 12주차-정인겸-0814

- 13주차/ingyeom/BOJ_11399.java
- 13주차/ingyeom/BOJ_11501.java
- 13주차/ingyeom/BOJ_1541.java
- 13주차/ingyeom/BOJ_1744.java
- 13주차/ingyeom/BOJ_2170.java
- 13주차/ingyeom/BOJ_2457.java
- 14주차/ingyeom/PGS_합승택시요금.java
> 13주차-정인겸-0824

- 13주차/daeho/BJ_11399.java
- 13주차/daeho/BJ_11501.java
- 13주차/daeho/BJ_1541.java
- 13주차/daeho/BJ_1744.java
- 13주차/daeho/BJ_2170.java
- 13주차/daeho/BJ_2457.java
- 14주차/daeho/PGS_등산코스 정하기.java
> 13주차-고대호-0824

- 13주차/yeseul/BOJ_1541.java
- 13주차/yeseul/BOJ_1744.java
- 13주차/yeseul/BOJ_2847.java
- 14주차/yeseul/PGM_택시합승요금/Solution.java
> 13주차-이예슬-0824

- 14주차/daeho/PGS_등산코스 정하기.java
- 14주차/daeho/PGS_디스크 컨트롤러.java
> 14주차-고대호-0827
